# Crie um Dockerfile utilizando a imagem chuanwen/cowsay.
FROM chuanwen/cowsay:latest

# Agora defina um ENTRYPOINT para a execução do comando.
ENTRYPOINT ["/usr/games/cowsay"]

# Utilize o CMD para definir uma mensagem padrão.
CMD ["#VQV Trybe"]

# Gere uma build e execute um contêiner baseado em sua imagem sem passar nenhum comando.