# Generated by Django 4.2.7 on 2023-11-27 17:23

from django.db import migrations, models
import playlists.validations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="length_in_seconds",
            field=models.IntegerField(
                validators=[playlists.validations.validate_music_length]
            ),
        ),
    ]
